### ISSUE TITLE
Not Injecting ek9 files

### ISSUE THREAD

**Issue by UltraMoonTrainer** [Project-PokeBots/SCVI_PokeManager#2]
The program is dumping them but i cannot write them back to the switch, the program just closes itself or freezes.

**Comment by 6A-Realm** [comment]
Hello, I fixed in the development branch

**Comment by 6A-Realm** [comment]
Merged into main branch, slot feature is not working yet. Make sure you have a file specifically named "inject.ek9" for the inject command to work
